exports.persons = [
    { name : 'Superman', alias: 'Clark Kent', superhuman : true, company : 'DC', team :  'Justice league', role : 'Hero' },
    { name : 'Batman', superhuman : false, alias :'Bruce Wayne', company : 'DC', team : 'Justice league', role : 'Hero' },
    { name : 'Aquaman', superhuman : true, alias : null, company : 'DC', team : 'Justice league', role : 'Hero' },
    { name : 'Green arrow', superhuman : false, alias : 'Oliver Queen', team : 'Justice league', role : 'Hero' },
    { name : 'Shazam', superhuman : true, alias : 'Billy Batson', company : 'DC', team : null, role : 'Hero' },
    { name : 'Flash', superhuman : true, alias : 'Barry Allen', company : 'DC', team : 'Justice league', role : 'Hero' }, 
    { name : 'Wonder woman', superhuman : true, alias : 'Princess Diana', company : 'DC', team : null, role : 'Hero' },
    { name : 'Cyborg', superhuman : false, alias : 'Vic Stone', company : 'DC', team : null, role : 'Hero' },
    { name : 'Nightwing', superhuman : false, alias : 'Dick Grayson', company : 'DC', team : null, role : 'Hero' },
    { name : 'Green lantern', superhuman : true, alias : 'Hal Jordan', company : 'DC', team : 'Justice league', role : 'Hero' },
    { name : 'Hawk girl', superhuman : true, alias : 'Shayera Hol', company : 'DC', team : 'Justice league', role : 'Hero' },
    { name : 'Hawk man', superhuman : true, alias : null, company : 'DC', team : 'Justice league', role : 'Hero' },
    { name : 'Raven', superhuman : true, alias : null, company : 'DC', team : null, role : 'Hero' },
    { name : 'Beast boy', superhuman : true, alias : 'Garfield Logan', company : 'DC', team : null, role : 'Hero' },
    { name : 'Supergirl', superhuman : true, alias : 'Kara Zor-El', company : 'DC', team : null, role : 'Hero' },
    { name : 'Joker', superhuman : false, alias : null, company : 'DC', team : null, role : 'Villian' },
    { name : 'Genral zodd', superhuman : true, alias : 'Dru-Zod', company : 'DC', team : null, role : 'Villian' },
    { name : 'Solomon grundy', superhuman : true, alias : 'Cyrus Gold', company : 'DC', team : null, role : 'Villian' },
    { name : 'Sinestro', superhuman : true, alais : 'Thall Sinestro', company : 'DC', team : null, role : 'Villian' }, 
    { name : 'Death stroke', superhuman : true, alias : 'Slade Wilson', company : 'DC', team : null, role : 'Villian' },
    { name : 'Harley quinn', superhuman : false, alias : 'Harleen Quinzel', company : 'DC', team : null, role : 'Villian' },
    { name : 'Bane', superhuman : true, alias : null, company : 'DC', team : null, role : 'Villian' },
    { name : 'Dark seid', superhuman : true, alias : null, company : 'DC', team : null, role : 'Villian' },
    { name : 'Dooms day', superhuman : true, alias : null, company : 'DC', team : null, role : 'Villian' },
    { name : 'Lex luthor', superhuman : false, alias : null, company : 'DC', team : null, role : 'Villian' },
    { name : 'Blue beatle', superhuman : true, alias : 'Jaime Reye', company : 'DC', team : null, role : 'Villian' },
    { name : 'Black adam', superhuman : true, alias : null, company : 'DC', team : null, role : 'Villian' },
    { name : 'Martian manhunter', superhuman : true, alias : 'John Jones', company : 'DC', team : 'Justice League', role : 'Hero' },
    { name : 'Killer frost', superhuman : true, alias : 'Caitlin Snow', company : 'DC', team : null, role : 'Villian' },
    { name : 'Ares', superhuman : true, alias : null, company : 'DC', team : null, role : 'Villian' },
    { name : 'Catwoman', superhuman : true, alias : 'Selina Kyle', company : 'DC', team : null, role : 'Villian' },
    { name : 'Starfire', superhuman : true, alias : 'Princess Koriandr', company : 'DC', team : null, role : 'Hero' },
    { name : 'Captain America', superhuman : true, alias : 'Steve Rodgers', company : 'Mavel', team : 'Avengers', role : 'Hero' },
    { name : 'Hulk', superhuman : true, alias : 'Bruce Banner', company : 'Marvel', team : 'Avengers', role : 'Hero' },
    { name : 'Black widow', superhuman : false, alias : 'Natasha Rominov', company : 'Marvel', team : 'Avengers', role : 'Hero' },
    { name : 'Iron man', superhuman : false, alias : 'Tony Stark', company : 'Marvel', team : 'Avengers', role : 'Hero' },
    { name : 'Codester', superhuman : true, alias : 'Nathan Moon' , company : 'HireVue', team : 'GaurdiansOf RaP', role : 'Hero' },
    { name : 'Tubulartyper', superhuman : true, alias : 'Ryan Jameson', company : 'HireVue', team : 'GaurdiansOf RaP', role : 'Hero' },
    { name : 'Careful cal', superhuman : true, alias : 'Calvin Jameson', company : 'HireVue', team : 'Plane awesome', role : 'Hero' },
    { name : 'Hawk eye', superhuman : false, alias : 'Clint Barton', company : 'Marvel', team : 'Avengers', role : 'Hero' },
    { name : 'Thor', superhuman : true, alias : null, company : 'Marvel', team : 'Avengers', role : 'Hero' },
    { name : 'Spider-man', superhuman : true, alias : 'Peter Parker', company : 'Marvel', team : null, role : 'Hero' },
    { name : 'Luke cage', superhuman : true, alias : null, company : 'Marvel', team : null, role : 'Hero' },
    { name : 'Dare devil', superhuman : false, alias : 'Mathew Murdock', team : null, role : 'Hero' },
    { name : 'Wolverine', superhuman : true, alias : 'James Howlet', team : 'X-men', role : 'Hero' },
    { name : 'Angel', superhuman : true, alias : 'Warren Worthington', team : 'X-men', role : 'Hero' },
    { name : 'Beast', superhuman : true, alias : 'Hank McCoy', team : 'X-men', role : 'Hero' },
    { name : 'Colosus', superhuman : true, alias : 'Piotr Rasputin', team : 'X-men', role : 'Hero' },
    { name : 'Cyclops', superhuman : true, alias : 'Scott Summers', team : 'X-men', role : 'Hero' },
    { name : 'Gambit', superhuman : true, alias : 'Remy JeBeau', team : 'X-men', role : 'Hero' },
    { name : 'Emma frost', superhuman : true, alias : null, team : 'X-men', role : 'Hero' },
    { name : 'Iceman', superhuman : true, alias : 'Bobby Drake', team : 'X-men', role : 'Hero' },
    { name : 'Jean grey', superhuman : true, alias : null, team : 'X-men', role : 'Hero' },
    { name : 'Jubilee', superhuman : true, alias : null, team : 'X-men', role : 'Hero' },
    { name : 'Kitty pride', superhuman : true, alias : 'Katherine Pride', team : 'X-men', role : 'Hero' },
    { name : 'Night crawler', superhuman : true, alias : 'Kurt Wagner', team : 'X-men', role : 'Hero' },
    { name : 'North star', superhuman : true, alias : 'Jean Beaubier', team : 'X-men', role : 'Hero' },
    { name : 'Psylocke', superhuman : true, alias : 'Elizabeth Braddock', team : 'X-men', role : 'Hero' },
    { name : 'Rogue', superhuman : true, alias : null, team : 'X-men', role : 'Hero' },
    { name : 'Storm', superhuman : true, alias : 'Ororo Munroe', team : 'X-men', role : 'Hero' },
    { name : 'X-23', superhuman : true, alias : 'Laura Kinney', team : 'X-men', role : 'Hero' },
    { name : 'Dead pool', superhuman : true, alais : 'Wade Willson', team : null, role : 'Villian' },
    { name : 'Star lord', superhuman : false, alias : 'Peter Quill', team : 'Gaurdians of the galaxy', role : 'Hero' },
    { name : 'Rocket raccoon', superhuman : true, alias : null, team : 'Gaurdians of the galaxy', role : 'Hero' },
    { name : 'Groot', superhuman : true, alias : null, team : 'Gaurdians of the galaxy', role : 'Hero' },
    { name : 'Gamora', superhuman : true, alias : 'Peter Quill', team : 'Gaurdians of the galaxy', role : 'Hero' },
    { name : 'Drax', superhuman : true, alias : 'Arthur Douglas', team : 'Gaurdians of the galaxy', role : 'Hero' },
]
